### ISSUE TITLE
Update the benchmark against Kryo 3.x and Fast 2.x

### ISSUE THREAD

**Issue by martin-g** [Mojang/blixtser#1]
Please update the benchmark [1] results in the README against latest Kryo (3.0.0)  and Fast (2.10)
1. https://github.com/Mojang/blixtser/blob/master/blixtser-benchmark/build.gradle

**Comment by amir343** [comment]
It's updated!

**Comment by martin-g** [comment]
That was fast !
Thank you !

@RuedigerMoeller  According to https://github.com/Mojang/blixtser/commit/4236b318a614d5daed7d066e88d0c08c061d0307 Fast 2 is actually a bit slower than Fast 1. I guess you will want to check the benchmark code.

**Comment by RuedigerMoeller** [comment]
that's true. versioning support and some more maintainabilty(no manual
inlining). however its performibg well given its a feature complete
implementation of jdk serialization without using unsafe. if i
enable  unsafe for array serialization it might even outperform. however
use of unsafe quickly crashes even for minor version mismatches of
sender+receiver (have removed that from fst therefore)

Am Donnerstag, 6. November 2014 schrieb Martin Grigorov :

**Comment by RuedigerMoeller** [comment]
btw: in fst 1.x there is fstunshared io streams which perform significantly better than standardstream using the unshared flag. not sure if this holds true for 2.x (2.x has not received as much optimizations yet)

**Comment by amir343** [comment]
fst is definitely one of the best implementations I've seen in this area. I can change benchmark for FST in any way you think it performs better. Just let me know.

**Comment by RuedigerMoeller** [comment]
I am on the road currently, will provide a pull request later this week.

**Comment by RuedigerMoeller** [comment]
There are many flaws in your comparision, so I have problems not to be rude:
1) blixter is not a serializer but an encoder. You should compare it to protobuff, SBE or similar encoders without support for custom serializing, cycle detection and nested objects + collections, custom handler methods (such as read/writeObject/readReplace/writeReplace) etc.
2) You are measuring the setup costs mostly as the object serialized is very small. Also you should test various object structures (example: https://github.com/RuedigerMoeller/fast-serialization/wiki/Benchmark)
3) for the fst test you are synchronizing on the output buffer ?!
4) Using unsafe for array serialization is a no go in practice, any version mismatch crashes the VM. Same goes for any cyclic structure (trust me, I learned it the hard way :-) ).

**Comment by amir343** [comment]
1) We're comparing the same features between blixtser and others. You can call it serializer, encoder etc. The purpose of comparison is not feature set but speed.
2) I thought by registering the class I can minimize the setup cost for fst. I'll definitely add various object structures
3) Oh, that was a left-over. I just removed it and I'll update the result for fairness.
4) Surely but we have a disclaimer and whoever wanna use blixtser should also take the risk for VM crashes and such.

**Comment by RuedigerMoeller** [comment]
1) that's like comparing comparing hashmap and array performance for keys from 1..100. The Array will be faster for this particular case ofc. . 
Serializers solve a much bigger task in saving/retrieving arbitrary object graphs (having to check many corner cases [inner classes, referenced objects being serializable, ...]). So even if you flag some features off, there will be additional checks. 
If you don't need true serialization, You won't use a generic serializer, that's why I pointed out your competition should be similar encoding libs (there many simple "serialization" libs e.g. protobuff, protostuff, but few full graph serializers and only 3 jdk compliant implementation (JDK, FST, JBoss). Kryo is inbetween.
2) this helps, however main setup time comes from new'ing/resetting of hashmaps & initialization stuff. 
In 2.x init time decreased against 1.x, so its slightly slower for very small objects. With your test, init 
time dominates actual serialization time.
3) ok
4) as been told, i already walked down the road of unsafe (and had to turnaround) .. however I plan to reintroduce an unsafe codec now that with 2.x stuff is pluggable. Its mostly for benchmarks, as in practice it turns out being too dangerous for most cases ..

**Comment by RuedigerMoeller** [comment]
could not resist:
move back to fst 1.63 and change the test to this (using **FSTObjectOutputNoShared** cut-corner impls):

``` java
package com.mojang.blixtser.benchmark;


import de.ruedigermoeller.serialization.*;

import java.io.IOException;

public class FastSerializer implements Serializer {

    final FSTObjectOutput out;
    FSTObjectInput in;

    byte[] buffer = new byte[4096];

    {
        FSTConfiguration fst = FSTConfiguration.createDefaultConfiguration();
        fst.setShareReferences(false);
        fst.setPreferSpeed(true);
        fst.registerClass(SampleValue.class);
        out = new FSTObjectOutputNoShared(fst);
        in = new FSTObjectInputNoShared(fst);
    }

    @Override
    public byte[] serialize(Object obj) {
        try {
            out.resetForReUse(buffer);
            out.writeObject(obj);
            return out.getBuffer();
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }

    @Override
    public Object deserialize(byte[] arr) {
        try {
            in.resetForReuseUseArray(arr);
            return in.readObject();
        } catch (IOException | ClassNotFoundException e) {
            throw new RuntimeException(e);
        }
    }
}
```

yields:

```
Benchmark                                                     Mode  Samples  Score   Error  Units
c.m.b.b.MicroBenchmark_AllModes.blixtser                     thrpt       10  5,472 ▒ 0,290  ops/s
c.m.b.b.MicroBenchmark_AllModes.fastSerializer               thrpt       10  4,981 ▒ 0,158  ops/s
c.m.b.b.MicroBenchmark_AllModes.java_built_in_serializer     thrpt       10  0,178 ▒ 0,002  ops/s
c.m.b.b.MicroBenchmark_AllModes.kryo                         thrpt       10  3,583 ▒ 0,127  ops/s
c.m.b.b.MicroBenchmark_AllModes.blixtser                      avgt       10  0,158 ▒ 0,010   s/op
c.m.b.b.MicroBenchmark_AllModes.fastSerializer                avgt       10  0,211 ▒ 0,004   s/op
c.m.b.b.MicroBenchmark_AllModes.java_built_in_serializer      avgt       10  5,766 ▒ 0,081   s/op
c.m.b.b.MicroBenchmark_AllModes.kryo                          avgt       10  0,295 ▒ 0,008   s/op
c.m.b.b.MicroBenchmark_AllModes.blixtser                    sample       78  0,156 ▒ 0,005   s/op
c.m.b.b.MicroBenchmark_AllModes.fastSerializer              sample       60  0,210 ▒ 0,002   s/op
c.m.b.b.MicroBenchmark_AllModes.java_built_in_serializer    sample       10  5,802 ▒ 0,095   s/op
c.m.b.b.MicroBenchmark_AllModes.kryo                        sample       40  0,286 ▒ 0,006   s/op
c.m.b.b.MicroBenchmark_AllModes.blixtser                        ss       10  0,158 ▒ 0,001      s
c.m.b.b.MicroBenchmark_AllModes.fastSerializer                  ss       10  0,207 ▒ 0,002      s
c.m.b.b.MicroBenchmark_AllModes.java_built_in_serializer        ss       10  5,510 ▒ 0,069      s
c.m.b.b.MicroBenchmark_AllModes.kryo                            ss       10  0,283 ▒ 0,003      s
```

(I7 laptop)

**Comment by amir343** [comment]
:)) 

I actually used FST 1.28 until today that someone asked me to benchmark against latest releases of both FST and Kryo!

**Comment by RuedigerMoeller** [comment]
I support still 1.x (fast + mature). 2.x is slightly slower, but has more features (versioning, different binary formats,..). Had no time to reoptimize (its mostly init, which only shows up in benches ..). You should use latest 1.x version: 1.63. Also use faster fst*NoShared streams.

**Comment by RuedigerMoeller** [comment]
on a side node if you put in a string array containg identical strings fst + kryo will rock all over a sudden :-). reference racking can pay off in manyreal world scenarios ..
